config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "groups#index"
  resources :groups, shallow: true do
    resources :messages, only: [:create, :index]
  end
  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
  accepts_nested_attributes_for :user_groups, allow_destroy: true
  has_many :messages

  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  def json_message
    {user_name: user.name, created_at: created_at.to_s(:datetime), content: content, image: image.url}
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  scope :not_current_user, -> (current_user){ where.not(id: current_user.id) }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :messages

  validates :name, presence: true
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  before_action :set_all_group, only: [:index]
  before_action :set_users, only: [:edit]

  def index
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    if @group.save
      redirect_to root_path, notice:'新しいグループを作成しました'
    else
      flash[:alert] = 'グループを作成できませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    @group.update(group_params)
    redirect_to root_path, notice:'グループ情報を更新しました'
  end

  private

  def group_params
    params.require(:group).permit(:name, {user_ids: []})
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_all_group
    @groups = current_user.groups
  end

  def set_users
    @users = @group.users.not_current_user(current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = current_user.messages.new(message_params)
    if message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(message.group) }
        format.json { render json: message.json_message}
      end
    else
      redirect_to group_messages_path(message.group.id), alert: 'メッセージを投稿できませんでした'
    end
  end

  def index
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
    @message = Message.new
    @messages = @group.messages
    @users = @group.users
    respond_to do |format|
      format.html { render :index }
      format.json {
        messages = @messages.includes(:user).map do |message|
          message.json_message
        end
        render json: messages
      }
    end
  end


  private
  def message_params
    params.require(:message).permit(:content, :image).merge(group_id: params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    users = User.where('name LIKE ?', "%#{params[:name]}%").not_current_user(current_user)
    respond_to do |format|
      format.json { render json: users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def first_message(group)
    group.messages.last
  end
end

app/views/groups/_group.html.haml
= link_to group_messages_path(group) do
  %li
    .group-name
      = group.name
    .newest-message
      = first_message(group).present? ? first_message(group).content : 'まだメッセージはありません'

app/views/groups/_sidebar.html.haml
.sidebar
  .sidebar__top
    .user-name
      = current_user.name
      .icons
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
        = link_to edit_user_registration_path(current_user) do
          %i.fa.fa-cog
  .sidebar__content
    %ul
      = render @groups

app/views/groups/_user.html.haml
.list_user.clearfix
  .list_user--name
    = user.name
  .list_user--button
    %a.delete{ href: '#' }
      %span 削除
  %input{ type: 'hidden', name: 'group[user_ids][]', value: user.id }

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for(@group, class: 'new_chat_group', id: 'new_chat_group') do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, id: 'chat_group_name', class: 'chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{ for: 'chat_group_チャットメンバーを追加' } チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ placeholder: '追加したいユーザー名を入力してください', type: 'text' }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{ for:  'chat_group_チャットメンバー' } チャットメンバー
      .chat-group-form__field--right
        #members-user
          .list_user.clearfix
            .list_user--name
              = current_user.name
            .list_user--button
              %a{ href: '#' }
            %input{ type: 'hidden', name: 'group[user_ids][]'  , value: current_user.id }
          = render partial: 'groups/user', collection: @users
        #chat-group-users
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit 'Save', class:'chat-group-form__action-btn'

app/views/groups/index.html.haml
.contents.clearfix
  = render partial: 'sidebar', locals: { groups: @groups }

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for(@group, class:"new_chat_group", id:"new_chat_group") do |f|
    %input{:name => "utf8", :type => "hidden", :value => "✓"}/
    %input{:name => "authenticity_token", :type => "hidden", :value => "AxFKlYEhD6eqX1PiZoTYQDANtKvgcFSXZQXHt5hyTl55/U/CHC5rtPavrcu2za65riz4tekZEy56vP6kEb2wYA=="}/
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class:"chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, id:"chat_group_name", class:"chat-group-form__input", placeholder:"グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .list_user.clearfix
          .list_user--name
            = current_user.name
          .list_user--button
            %a{ href: '#' }
        #chat-group-users
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/layouts/_flash.html.haml
.js-flash-message
  - flash.each do |key, value|
    %div{ class: 'alert alert-#{key}'}
      .container
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    = render partial: 'layouts/flash'
  = yield

app/views/messages/_message.html.haml
%li
  .meassage.clearfix
    .message__username
      = message.user.name
    .message__time
      = message.created_at.to_s(:datetime)
  %p.message__content
    = message.content
  .message__image
    = image_tag(message.image, class: 'message-image')

app/views/messages/index.html.haml
.contents.clearfix
  = render partial:'groups/sidebar', locals: { groups: @groups }
  .main
    .group-top.clearfix
      .group-top__left
        .group-top__left--group-name
          = @group.name
        .group-top__left--member
          %ul
            %li
              Members:
            = render @users
      .group-top__right
        = link_to 'Edit', edit_group_path(@group)
    .group-content
      %ul.messages
        = render @messages
    .group-bottom.clearfix
      = form_for([@group, @message],html: { class: 'js-message-form' }) do |f|
        .form-content
          = f.text_field :content, placeholder: 'type a message', class: 'js-message-text'
        .group-bottom__right
          = f.label :image do
            %i.fa.fa-picture-o
            = f.file_field :image, class: 'input-image'
          = f.submit 'send', class: 'js-message-submit'

app/views/users/_user.html.haml
%li
  = user.name